#!/bin/bash
# our comment is here
echo "The current directory is:"
pwd
echo "The user logged in is:"
whoami

FILE=databases
inc=8000
    while read LINE; do
	inc=$[inc+1]
	export VAR_BASE=$LINE
	echo "Line $inc: $VAR_BASE"
	docker run -d -e "BASE_NAME=$VAR_BASE" --add-host 1csrv01:192.168.20.3 --add-host 1csrv02:192.168.20.4 --rm --publish $inc:80 my-apache-1c
    done < $FILE
